// Product catalogue for Parakh Creation & Parakh Collection
// EDIT ME: fill in real product names, prices (in INR) and specification text below.
// price: set a number (e.g. 2499) to show a price, or leave null to show "Price on request".
// specs: short line(s) about fabric, work, length/size — shown in the product detail panel.
const PRODUCTS = [
  {
    id: "SR01",
    name: "Saree — No. 01",
    category: "saree",
    img: "assets/products/saree_01.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR02",
    name: "Saree — No. 02",
    category: "saree",
    img: "assets/products/saree_02.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR03",
    name: "Saree — No. 03",
    category: "saree",
    img: "assets/products/saree_03.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR04",
    name: "Saree — No. 04",
    category: "saree",
    img: "assets/products/saree_04.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR05",
    name: "Saree — No. 05",
    category: "saree",
    img: "assets/products/saree_05.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR06",
    name: "Saree — No. 06",
    category: "saree",
    img: "assets/products/saree_06.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR07",
    name: "Saree — No. 07",
    category: "saree",
    img: "assets/products/saree_07.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR08",
    name: "Saree — No. 08",
    category: "saree",
    img: "assets/products/saree_08.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR09",
    name: "Saree — No. 09",
    category: "saree",
    img: "assets/products/saree_09.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR10",
    name: "Saree — No. 10",
    category: "saree",
    img: "assets/products/saree_10.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR11",
    name: "Saree — No. 11",
    category: "saree",
    img: "assets/products/saree_11.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR12",
    name: "Saree — No. 12",
    category: "saree",
    img: "assets/products/saree_12.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR13",
    name: "Saree — No. 13",
    category: "saree",
    img: "assets/products/saree_13.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR14",
    name: "Saree — No. 14",
    category: "saree",
    img: "assets/products/saree_14.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR15",
    name: "Saree — No. 15",
    category: "saree",
    img: "assets/products/saree_15.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR16",
    name: "Saree — No. 16",
    category: "saree",
    img: "assets/products/saree_16.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR17",
    name: "Saree — No. 17",
    category: "saree",
    img: "assets/products/saree_17.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR18",
    name: "Saree — No. 18",
    category: "saree",
    img: "assets/products/saree_18.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR19",
    name: "Saree — No. 19",
    category: "saree",
    img: "assets/products/saree_19.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR20",
    name: "Saree — No. 20",
    category: "saree",
    img: "assets/products/saree_20.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "SR21",
    name: "Saree — No. 21",
    category: "saree",
    img: "assets/products/saree_21.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST01",
    name: "Suit Set — No. 01",
    category: "suit",
    img: "assets/products/suit_01.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST02",
    name: "Suit Set — No. 02",
    category: "suit",
    img: "assets/products/suit_02.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST03",
    name: "Suit Set — No. 03",
    category: "suit",
    img: "assets/products/suit_03.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST04",
    name: "Suit Set — No. 04",
    category: "suit",
    img: "assets/products/suit_04.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST05",
    name: "Suit Set — No. 05",
    category: "suit",
    img: "assets/products/suit_05.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST06",
    name: "Suit Set — No. 06",
    category: "suit",
    img: "assets/products/suit_06.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST07",
    name: "Suit Set — No. 07",
    category: "suit",
    img: "assets/products/suit_07.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST08",
    name: "Suit Set — No. 08",
    category: "suit",
    img: "assets/products/suit_08.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST09",
    name: "Suit Set — No. 09",
    category: "suit",
    img: "assets/products/suit_09.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST10",
    name: "Suit Set — No. 10",
    category: "suit",
    img: "assets/products/suit_10.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST11",
    name: "Suit Set — No. 11",
    category: "suit",
    img: "assets/products/suit_11.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST12",
    name: "Suit Set — No. 12",
    category: "suit",
    img: "assets/products/suit_12.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST13",
    name: "Suit Set — No. 13",
    category: "suit",
    img: "assets/products/suit_13.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST14",
    name: "Suit Set — No. 14",
    category: "suit",
    img: "assets/products/suit_14.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST15",
    name: "Suit Set — No. 15",
    category: "suit",
    img: "assets/products/suit_15.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST16",
    name: "Suit Set — No. 16",
    category: "suit",
    img: "assets/products/suit_16.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST17",
    name: "Suit Set — No. 17",
    category: "suit",
    img: "assets/products/suit_17.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST18",
    name: "Suit Set — No. 18",
    category: "suit",
    img: "assets/products/suit_18.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST19",
    name: "Suit Set — No. 19",
    category: "suit",
    img: "assets/products/suit_19.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST20",
    name: "Suit Set — No. 20",
    category: "suit",
    img: "assets/products/suit_20.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
  {
    id: "ST21",
    name: "Suit Set — No. 21",
    category: "suit",
    img: "assets/products/suit_21.jpg",
    price: null,
    specs: "Fabric, work and size details to be added.",
  },
];
